on:
  push:
    branches:
      - main
name: "Relase Source Code"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
    - name: Upload Release
      uses:  ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
